FROM leochan007/python36

LABEL MAINTAINER leo chan <leochan007@163.com>

ENV DEBIAN_FRONTEND noninteractive
ENV LANG C.UTF-8

RUN pip3 install -U bson pymongo pandas numpy xlsxwriter pyyaml apscheduler
