MONGODB_URL: "mongodb://root:example@127.0.0.1:27017/admin?authSource=admin"

OUTPUT_FILE: report.xlsx

MAIL:
  host:
    smtp.exmail.qq.com
  port:
    465
  username:
    do-not-reply@alphacar.io
  password:
    al*@#1Jks%KmyLA
  to:
    - test@alphacar.io
    #- leo.chen@alphacar.io

CRON:
  type:
    interval
  conf:
  #all
    timezone:
      ""
    start_date:
      ""
    end_date:
      ""
  #interval
    weeks:
      "1"
    days:
      "7"
    hours:
      "0"
    minutes:
      "0"
    seconds:
      "0"
