MONGODB_URL: "mongodb://root:example@127.0.0.1:27017/admin?authSource=admin"

OUTPUT_FILE: report.xlsx

MAIL:
  host:
    smtp.exmail.qq.com
  port:
    465
  username:
    do-not-reply@alphacar.io
  password:
    al*@#1Jks%KmyLA
  to:
    - test@alphacar.io
    #- leo.chen@alphacar.io

CRON:
  type:
    date
  conf:
    timezone:
      ""
    run_date:
      "2019-02-14 17:05:20"
